services:
  postgresql:
    image: postgres:15.1
    environment:
      POSTGRES_USER: "kotak"
      POSTGRES_DB: "kotak"
      POSTGRES_PASSWORD: "kotak"
      PGDATA: /var/lib/postgresql/data/pgdata
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5432:5432"
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data/pgdata:z
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:z
      - ./postgresql.conf:/etc/postgresql.conf:z